# Trabajo Quiniela con pyspark

## Descripcion

In [1]:
import sys
print(sys.executable)

c:\Users\Gines\AppData\Local\Programs\Python\Python312\python.exe

### Imports

In [2]:
import pandas as pd
import pandasql as ps

## 1- Lectura del fichero

In [3]:
jornada_datos = '14'
ruta = f'C:/Users/Gines/Desktop/webscrap_liga/datos24-25/jornada_{jornada_datos}/'

Lectura del fichero de Resultados

In [4]:
ruta_excel_resultados = ruta + "resultados.xlsx"

In [5]:
df_pd_resultados = pd.read_excel(ruta_excel_resultados)

In [6]:
df_pd_resultados.head(4)

,Unnamed: 0,fecha,hora,local,visitante,gol_local,gol_visitante,arbitro,jornada
0,0,JUE 15.08.2024,19:00,ATHLETIC CLUB,GETAFE CF,1,1,Alejandro Muñiz Ruiz,1
1,1,JUE 15.08.2024,21:30,REAL BETIS,GIRONA FC,1,1,Miguel Ángel Ortiz Arias,1
2,2,VIE 16.08.2024,19:00,RC CELTA,DEPORTIVO ALAVÉS,2,1,Alejandro Quintero González,1
3,3,VIE 16.08.2024,21:30,UD LAS PALMAS,SEVILLA FC,2,2,Francisco José Hernández Maeso,1

Lectura del fichero de Clasificacion

In [7]:
ruta_excel_clasificacion = ruta + "clasificacion.xlsx"

In [8]:
df_pd_clasificacion = pd.read_excel(ruta_excel_clasificacion)

In [9]:
df_clasificacion_1 = df_pd_clasificacion

In [10]:
#df_pd_clasificacion.head(5)

Lectura del fichero Clasi_casa

In [11]:
ruta_excel_clasi_casa = ruta + "clasi_casa.xlsx"

In [12]:
df_pd_clasiCasa = pd.read_excel(ruta_excel_clasi_casa)

In [13]:
#df_pd_clasiCasa.head(5)

Lectura del fichero Clasi_fuera

In [14]:
ruta_excel_clasi_fuera = ruta + "clasi_fuera.xlsx"

In [15]:
df_pd_clasiFuera = pd.read_excel(ruta_excel_clasi_fuera)

In [16]:
#df_pd_clasiFuera.head(5)

# 2- Union de los dataframes

In [17]:
result = df_pd_resultados
clasi = df_pd_clasificacion
clasi_1 = df_clasificacion_1
clasi_casa = df_pd_clasiCasa
clasi_casa1 = df_pd_clasiCasa
clasi_fuera = df_pd_clasiFuera
clasi_fuera1 = df_pd_clasiFuera

In [18]:
query = """
    SELECT R.fecha, R.hora, R.local, R.visitante, R.gol_local, R.gol_visitante, R.arbitro, R.jornada, C.posicion as pos_local, C.puntos as pts_local, C.PJ as PJ_local, C.PG as PG_local, C.PE as PE_local, C.PP as PP_local, C.GF as GF_local, C.GC as GC_local, C.DG as DG_local, C1.posicion as pos_visi, C1.puntos as pts_visi, C1.PJ as PJ_visi, C1.PG as PG_visi, C1.PE as PE_visi, C1.PP as PP_visi, C1.GF as GF_visi, C1.GC as GC_visi, C1.DG as DG_visi, casa.posicion as pos_loc_C, casa.puntos as pts_loc_C, casa.PJ as PJ_loc_C, casa.PG as PG_loc_C, casa.PE as PE_loc_C, casa.PP as PP_loc_C, casa.GF as GF_loc_C, casa.GC as GC_loc_C, casa.DG as DG_loc_C, fuera.posicion as pos_loc_F, fuera.puntos as pts_loc_F, fuera.PJ as PJ_loc_F, fuera.PG as PG_loc_F, fuera.PE as PE_loc_F, fuera.PP as PP_loc_F, fuera.GF as GF_loc_F, fuera.GC as GC_loc_F, fuera.DG as DG_loc_F, casa1.posicion as pos_vis_C, casa1.puntos as pts_vis_C, casa1.PJ as PJ_vis_C, casa1.PG as PG_vis_C, casa1.PE as PE_vis_C, casa1.PP as PP_vis_C, casa1.GF as GF_vis_C, casa1.GC as GC_vis_C, casa1.DG as DG_vis_C, fuera1.posicion as pos_vis_F, fuera1.puntos as pts_vis_F, fuera1.PJ as PJ_vis_F, fuera1.PG as PG_vis_F, fuera1.PE as PE_vis_F, fuera1.PP as PP_vis_F, fuera1.GF as GF_vis_F, fuera1.GC as GC_vis_F, fuera1.DG as DG_vis_F
    FROM result R
    LEFT JOIN clasi C ON R.local = C.equipo AND R.jornada = C.jornada
    LEFT JOIN clasi_1 C1 ON R.visitante = C1.equipo AND R.jornada = C1.jornada
    LEFT JOIN clasi_casa casa ON R.local = casa.equipo AND R.jornada = casa.jornada
    LEFT JOIN clasi_fuera fuera ON R.local = fuera.equipo AND R.jornada = fuera.jornada
    LEFT JOIN clasi_casa1 casa1 ON R.visitante = casa1.equipo AND R.jornada = casa1.jornada
    LEFT JOIN clasi_fuera1 fuera1 ON R.visitante = fuera1.equipo AND R.jornada = fuera1.jornada
"""

In [19]:
df_total = ps.sqldf(query, locals())

In [20]:
df_total.head(6)

,fecha,hora,local,visitante,gol_local,gol_visitante,arbitro,jornada,pos_local,pts_local,...,DG_vis_C,pos_vis_F,pts_vis_F,PJ_vis_F,PG_vis_F,PE_vis_F,PP_vis_F,GF_vis_F,GC_vis_F,DG_vis_F
0,JUE 15.08.2024,19:00,ATHLETIC CLUB,GETAFE CF,1,1,Alejandro Muñiz Ruiz,1,16,1.0,...,0.0,10,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
1,JUE 15.08.2024,21:30,REAL BETIS,GIRONA FC,1,1,Miguel Ángel Ortiz Arias,1,13,1.0,...,0.0,9,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
2,VIE 16.08.2024,19:00,RC CELTA,DEPORTIVO ALAVÉS,2,1,Alejandro Quintero González,1,1,3.0,...,0.0,13,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
3,VIE 16.08.2024,21:30,UD LAS PALMAS,SEVILLA FC,2,2,Francisco José Hernández Maeso,1,6,1.0,...,0.0,11,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
4,SAB 17.08.2024,19:00,CA OSASUNA,CD LEGANÉS,1,1,Juan Luis Pulido Santana,1,14,1.0,...,0.0,12,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
5,SAB 17.08.2024,21:30,VALENCIA CF,FC BARCELONA,1,2,José María Sánchez Martínez,1,19,0.0,...,0.0,15,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0

In [21]:
df_total.count()

fecha        140
hora         140
local        140
visitante    140
gol_local    140
            ...
PE_vis_F     140
PP_vis_F     140
GF_vis_F     140
GC_vis_F     140
DG_vis_F     140
Length: 62, dtype: int64

In [22]:
df_total = df_total.sort_values(by = 'jornada', ascending=True)

In [23]:
import os
directory = ruta
csv_path = os.path.join(directory, 'df_total.csv')

# Verificar y crear el directorio si no existe
if not os.path.exists(directory):
    os.makedirs(directory)
csv_path = directory + 'df_total.xlsx'
df_total.to_excel(csv_path, index = False)

In [24]:
# #función para eliminar datos de un csv
# file = open("df_total.xlsx", "w")
# file.close()
# #función para meter datos a un csv
# df_pd_total.to_excel('df_total.xlsx')

## Lectura df cuotas

In [ ]:
ruta_cuotas = 'C:/Users/gines/Desktop/webscrap_liga/SP1.csv'

In [ ]:
df_pd_cuotas = df_pd_resultados = pd.read_csv(ruta_cuotas)

In [ ]:
reemplazos = {'Almeria': 'UD ALMERÍA', 'Sevilla': 'SEVILLA FC','Sociedad':'REAL SOCIEDAD','Las Palmas':'UD LAS PALMAS',
              'Ath Bilbao':'ATHLETIC CLUB','Celta':'RC CELTA','Villarreal':'VILLARREAL CF','Getafe':'GETAFE CF',
             'Cadiz':'CÁDIZ CF','Ath Madrid': 'ATLÉTICO DE MADRID','Vallecano':'RAYO VALLECANO','Valencia':'VALENCIA CF',
             'Girona':'GIRONA FC','Mallorca':'RCD MALLORCA','Real Madrid':'REAL MADRID','Osasuna':'CA OSASUNA','Betis':'REAL BETIS',
             'Barcelona':'FC BARCELONA','Alaves':'DEPORTIVO ALAVÉS','Granada':'GRANADA CF'}

In [ ]:
df_pd_cuotas['HomeTeam'] = df_pd_cuotas['HomeTeam'].replace(reemplazos)
df_pd_cuotas['AwayTeam'] = df_pd_cuotas['AwayTeam'].replace(reemplazos)
df_pd_cuotas

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,SP1,11/08/2023,18:30,UD ALMERÍA,RAYO VALLECANO,0,2,A,0,2,...,1.64,0.00,1.85,2.08,1.86,2.07,1.91,2.09,1.86,2.01
1,SP1,11/08/2023,21:00,SEVILLA FC,VALENCIA CF,1,2,A,0,0,...,1.61,-0.50,1.94,1.99,1.94,1.98,1.96,2.00,1.93,1.94
2,SP1,12/08/2023,16:00,REAL SOCIEDAD,GIRONA FC,1,1,D,1,0,...,1.72,-0.75,2.05,1.75,2.10,1.82,2.14,1.90,2.04,1.82
3,SP1,12/08/2023,18:30,UD LAS PALMAS,RCD MALLORCA,1,1,D,1,0,...,1.40,-0.25,2.18,1.77,2.20,1.77,2.21,1.79,2.15,1.75
4,SP1,12/08/2023,20:30,ATHLETIC CLUB,REAL MADRID,0,2,A,0,2,...,1.89,0.25,1.99,1.94,1.99,1.93,2.10,1.96,1.95,1.90
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
254,SP1,25/02/2024,13:00,CÁDIZ CF,RC CELTA,2,2,D,0,1,...,1.47,0.25,1.85,2.08,1.85,2.09,1.86,2.12,1.80,2.07
255,SP1,25/02/2024,15:15,REAL BETIS,ATHLETIC CLUB,3,1,H,2,1,...,1.71,0.50,1.85,2.08,1.84,2.10,1.87,2.14,1.80,2.09
256,SP1,25/02/2024,17:30,UD LAS PALMAS,CA OSASUNA,1,1,D,0,0,...,1.54,-0.25,2.10,1.83,2.09,1.85,2.12,1.85,2.06,1.80
257,SP1,25/02/2024,20:00,REAL MADRID,SEVILLA FC,1,0,H,0,0,...,2.64,-1.75,2.06,1.87,2.06,1.86,2.09,1.89,1.99,1.85
258,SP1,26/02/2024,20:00,GIRONA FC,RAYO VALLECANO,3,0,H,0,0,...,2.09,-0.75,1.84,2.06,1.85,2.09,1.88,2.11,1.82,2.04